---
# Because of the high debug level enabled for LRC daemons, the root drives
# fill up rather quickly.  The drives fill up before the daily logrotate can
# run so we rotate every 6 hours and keep 3 days worth.  This can be adjusted
# as needed.  Logrotate already runs daily at 06:25 so there are 3 additional
# scheduled cronjobs to rotate 4x daily.

- name: "Write custom ceph logrotate config"
  template:
    src: ceph-common.logrotate
    dest: /etc/logrotate.d/ceph-common

- name: "Create cronjob to logrotate every 6 hours"
  cron:
    name: "Logrotate ceph logs every 6 hours"
    minute: "25"
    hour: "0,12,18"
    job: "/usr/sbin/logrotate -f /etc/logrotate.d/ceph-common"
    user: root
