---
- name: Ensure ceph packages are not present.
  yum:
    name: "{{ item }}"
    state: absent
  with_items: ceph_packages
  tags:
    - remove-ceph

- name: Define rpm_packages.
  set_fact:
    rpm_packages: "{{ packages | list }}"
  when: rpm_packages is not defined

- name: Install packages
  yum:
    name: "{{ item }}"
    state: present 
  with_items: rpm_packages
