---
- name: Ensure ceph packages are not present.
  yum:
    name: "{{ item }}"
    state: absent
  with_items: ceph_packages
  tags:
    - remove-ceph

- name: Install packages
  yum:
    name: "{{ item }}"
    state: present 
  with_items: packages
