---
# Where to download ISOs
iso_dir: /var/lib/cobbler/isos
# Mount point to use for ISOs during import
iso_mount: /mnt/iso

users_digest_lines:
 - "cobbler:Cobbler:a4fa62c1597fca6d8cf27b1325b0ae6a"

settings:
  - name: yum_post_install_mirror
    value: 0
  - name: signature_url
    value: http://cobbler.github.io/signatures/2.6.x/latest.json
  - name: server
    value: "{{ ip }}"
  - name: next_server
    value: "{{ ip }}"
  - name: pxe_just_once
    value: 1

kickstarts:
  - cephlab_rhel.ks
  - cephlab_ubuntu.preseed
  
snippets:
  - cephlab_user
  - cephlab_hostname
  - cephlab_apt-mirror_hack
  - cephlab_packages_rhel
  - cephlab_rc_local
  - cephlab_rhel_disks
  - cephlab_post_install_kernel_options
  - cephlab_ubuntu_network

scripts:
  - cephlab_preseed_late

triggers:
  - install/post/cephlab_ansible.sh

ansible_user_ssh_keys: []

ansible_user: ''
ansible_user_uid_: ''

# A list of lines to add to resolv.conf and resolv.conf.d/base
# An example:
#   resolvconf:
#      - "nameserver x.x.x.x"
#      - "search an.example.com"
resolvconf: []
