---
- include: apt_systems.yml
  when: ansible_pkg_mgr == "apt"

# Yum systems support is not implemented yet.
- include: yum_systems.yml
  when: ansible_pkg_mgr == "yum"

# Set up the different users that teuthology uses
- include: setup_users.yml

- name: Ship /etc/teuthology.yaml
  template:
    src: teuthology.yaml
    dest: /etc/teuthology.yaml
    mode: 0755

# Serve logs over HTTP
- include: setup_log_access.yml
