---
- import_tasks: apt_systems.yml
  when: ansible_pkg_mgr == "apt"

# Yum systems support is not implemented yet.
- import_tasks: yum_systems.yml
  when: ansible_pkg_mgr == "yum"

# Set up the different users that teuthology uses
- import_tasks: setup_users.yml

- name: Ship /etc/teuthology.yaml
  template:
    src: teuthology.yaml
    dest: /etc/teuthology.yaml
    mode: 0755
  tags:
    - config

# Serve logs over HTTP
- import_tasks: setup_log_access.yml
  tags:
    - logs
