---
- name: Create users
  user:
    name: "{{ item }}"
    state: present
    shell: /bin/bash
  with_items: "{{ teuthology_users }}"
  tags:
    - user

- name: Clone the teuthology repo
  git:
    repo: "{{ teuthology_repo }}"
    dest: /home/{{ item }}/src/teuthology_master
  sudo_user: "{{ item }}"
  with_items: "{{ teuthology_users }}"
  tags:
    - repos

- name: Run bootstrap
  shell: NO_CLOBBER=true ./bootstrap
  args:
    chdir: /home/{{ item }}/src/teuthology_master/
  sudo_user: "{{ item }}"
  with_items: "{{ teuthology_users }}"
  register: bootstrap
  changed_when: bootstrap.stdout_lines[-1]|length > 60
  tags:
    - repos
  
- name: Add teuthology scripts to PATH
  lineinfile:
    dest: /home/{{ item }}/.profile
    regexp: teuthology_master
    line: 'PATH="$HOME/src/teuthology_master/virtualenv/bin:$PATH"'
  sudo_user: "{{ item }}"
  with_items: "{{ teuthology_users }}"

- name: Ensure teuthology is usable
  shell: "./teuthology --version"
  args:
    chdir: /home/{{ item }}/src/teuthology_master/virtualenv/bin/
  sudo_user: "{{ item }}"
  with_items: "{{ teuthology_users }}"
  changed_when: false
