---
# Red Hat Subscription Manager credentials
subscription_manager_activationkey: ""
subscription_manager_org: ""

# Repos to enable in Red Hat Subscription Manager
rhsm_repos: []

kerberos_realm: EXAMPLE.COM

epel_mirror_baseurl: "http://dl.fedoraproject.org/pub/epel"
epel_mirrorlist: "http://mirrors.fedoraproject.org"
epel_repos:
  epel:
    name: "Extra Packages for Enterprise Linux"
    baseurl: "{{ epel_mirror_baseurl }}/{{ ansible_distribution_major_version }}/$basearch"
    mirrorlist: "{{ epel_mirrorlist }}/metalink?repo=epel-{{ ansible_distribution_major_version }}&arch=$basearch"
    failovermethod: priority
    # ternary requires ansible >= 1.9
    enabled: "{{ enable_epel | ternary(1, 0) }}"
    gpgcheck: 0
  epel-testing:
    name: "Extra Packages for Enterprise Linux - Testing"
    baseurl: "{{ epel_mirror_baseurl }}/testing/{{ ansible_distribution_major_version }}/$basearch"
    mirrorlist: "{{ epel_mirrorlist }}/metalink?repo=testing-epel{{ ansible_distribution_major_version }}&arch=$basearch"
    failovermethod: priority
    enabled: 0
    gpgcheck: 0

enable_epel: true
