---
# Red Hat Subscription Manager credentials
subscription_manager_activationkey: ""
subscription_manager_org: ""

# Repos to enable in Red Hat Subscription Manager
rhsm_repos: []

kerberos_realm: EXAMPLE.COM

epel_repos:
  epel:
    name: "Extra Packages for Enterprise Linux"
    baseurl: "{{ epel_mirror_baseurl }}/{{ ansible_distribution_major_version }}/$basearch"
    enabled: 1
    gpgcheck: 0
  epel-testing:
    name: "Extra Packages for Enterprise Linux - Testing"
    baseurl: "{{ epel_mirror_baseurl }}/testing/{{ ansible_distribution_major_version }}/$basearch"
    enabled: 0
    gpgcheck: 0
