---
- name: Ensure /var/log/pcp is owned by pcp
  file:
    path: /var/log/pcp
    owner: "{{ pcp_user }}"
    group: "{{ pcp_user }}"
    recurse: yes
  # http://tracker.ceph.com/issues/16119
  failed_when: false
