---
- name: Upload a dummy nfs export so that the nfs kernel server starts.
  template:
    src: ../../templates/exports
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify:
    - start nfs-server
  tags:
    - nfs

- name: Stop firewalld
  service:
    name: firewalld
    state: stopped


- name: Get hostname.
  command: hostname
  register: existing_hostname
  changed_when: false

- name: Remove lab domain from hostname.
  shell: hostname | cut -d'.' -f1
  register: new_hostname
  when: existing_hostname.stdout.find("{{ lab_domain | mandatory }}") != -1

- name: Set hostname.
  hostname:
     name: "{{ new_hostname.stdout }}"
  when: existing_hostname.stdout.find("{{ lab_domain | mandatory }}") != -1

# Install and configure cpan and Amazon::S3
- include: ../cpan.yml
  tags:
    - cpan
