---
- name: Set path to IPMI credentials
  set_fact:
      ipmi_creds_path: "{{ secrets_path }}/ipmi.yml"
  when: ipmi_creds_path is undefined

- name: Include IPMI credentials
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ipmi_creds_path }}"
    - empty.yml
  no_log: true
