---
- name: Include cobbler keys.
  include_vars: "{{ secrets_path | mandatory }}/cobbler_keys.yml"
  no_log: true
  tags:
    - vars

- name: Write cobbler keys
  copy: content="{{ item.data }}" dest="{{ item.path }}" mode=600
  with_items: cobbler_keys["{{ ansible_hostname}}"]
  no_log: true

- name: Include package type specific vars.
  include_vars: "{{ ansible_pkg_mgr }}_systems.yml"

- include: yum_systems.yml
  when: ansible_pkg_mgr == "yum"

- include: apt_systems.yml
  when: ansible_pkg_mgr == "apt"

- name: Start cobbler
  service:
    name: "{{ cobbler_service }}"
    state: started
    enabled: yes

- name: Start httpd
  service:
    name: "{{ httpd_service }}"
    state: started
    enabled: yes

- name: Update settings
  include: settings.yml

# TODO populate systems

- include: fetch_cm_repos.yml
  tags:
   - cm_repos

- include: upload_templates.yml
  tags:
    - templates

- include: distro_prep.yml
  tags:
    - distros

- name: Restart cobbler
  service:
    name: "{{ cobbler_service }}"
    state: restarted
  changed_when: false

- include: populate_systems.yml
  tags:
    - systems
