---
- name: Upload kickstarts and preseeds.
  template:
    src: "kickstarts/{{ item }}"
    dest: "/var/lib/cobbler/kickstarts/{{ item }}"
    owner: root
    group: root
    mode: 0644 
  with_items:
    - cephlab_trusty.preseed
    - cephlab_rhel.ks
  tags:
    - kickstarts

- name: Upload snippets
  template:
    src: "snippets/{{ item }}"
    dest: "/var/lib/cobbler/snippets/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - cephlab_user
    - cephlab_hostname
    - cephlab_apt-mirror_hack
    - cephlab_packages_rhel
  tags:
    - snippets

- name: Upload scripts.
  template:
    src: "scripts/{{ item }}"
    dest: "/var/lib/cobbler/scripts/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - cephlab_preseed_late
  tags:
    - scripts
