---
- name: Enable dynamic settings modification
  # Escape the colon below so the line will parse
  lineinfile: dest=/etc/cobbler/settings regexp=^allow_dynamic_settings line="allow_dynamic_settings{{':'}} 1"
  register: dynamic_settings

- name: Restart cobbler
  service:
    name: "{{ cobbler_service }}"
    state: restarted
  when: dynamic_settings|changed

- name: Update settings
  command: cobbler setting edit --name={{ item.name }} --value={{ item.value}}
  with_items: settings
