---
- name: Upload items in /etc
  template:
    src: "etc/{{ item }}"
    dest: "/etc/cobbler/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items: etc_files
  tags:
    - etc

- name: Upload kickstarts and preseeds.
  template:
    src: "kickstarts/{{ item }}"
    dest: "/var/lib/cobbler/kickstarts/{{ item }}"
    owner: root
    group: root
    mode: 0644 
  with_items: kickstarts
  tags:
    - kickstarts

- name: Upload snippets
  template:
    src: "snippets/{{ item }}"
    dest: "/var/lib/cobbler/snippets/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items: snippets
  tags:
    - snippets

- name: Upload scripts.
  template:
    src: "scripts/{{ item }}"
    dest: "/var/lib/cobbler/scripts/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items: scripts
  tags:
    - scripts

- name: Upload triggers.
  template:
    src: "triggers/{{ item }}"
    dest: "/var/lib/cobbler/triggers/{{ item }}"
    owner: root
    group: root
    mode: 0744
  with_items: triggers
  tags:
    - triggers
