---
# Partition a data drive, like the nvme devices in smithi.  Only included
# if partition_dict is defined.

- name: Write a new partition table to {{ drive_to_partition }}
  # -s: don't prompt for "are you sure"
  command: "parted -s {{ drive_to_partition }} mktable msdos"

- name: "Write partition entries to {{ drive_to_partition }}"
  command: "parted {{ drive_to_partition }} unit '%' mkpart primary {{ item }}"
  with_items:
    - "0 25"
    - "25 50"
    - "50 75"
    - "75 100"

- name: "Add /scratch_devs for {{ drive_to_partition }} p1"
  lineinfile:
    dest: /scratch_devs
    create: yes
    owner: root
    group: root
    mode: 0644
    line: "{{ drive_to_partition }}{{ item }}"
  with_items:
    - p1
    - p2
    - p3
    - p4
