---
# Partition a data drive, like the nvme devices in smithi.  Only included
# if drives_to_partition is defined.

- name: "Write a new partition table to {{ item.value.device }}"
  command: "parted -s {{ item.value.device }} mktable gpt"
  with_dict: "{{ drives_to_partition }}"

- name: "Write partition entries to {{ item.0.device }}"
  command: "parted {{ item.0.device }} unit '{{ item.0.unit }}' mkpart foo {{ item.1 }}"
  with_subelements:
    - "{{ drives_to_partition }}"
    - sizes

- name: "Add /scratch_devs for {{ item.0.device }}"
  lineinfile:
    dest: /scratch_devs
    create: yes
    owner: root
    group: root
    mode: 0644
    line: "{{ item.0.device }}{{ item.1 }}"
  with_subelements:
    - "{{ drives_to_partition }}"
    - scratch_devs
    - flags:
      # In case you want to partition a drive but not use it as a scratch device
      skip_missing: True
