---
- name: Edit lvm.conf to support LVM on kRBD.
  lineinfile:
    dest: /etc/lvm/lvm.conf
    regexp: "# types ="
    line: 'types = [ "rbd", 16 ]'
    backrefs: yes
    state: present

- include_tasks: configure_lvm.yml
  when: (logical_volumes is defined) or
        (volume_groups is defined) or
        (quick_lvs_to_create is defined)
