---
# loading vars
- include: vars.yml
  tags:
    - vars

- name: Set a high max open files limit for the teuthology user.
  template:
    src: security_limits.conf
    dest: "/etc/security/limits.d/{{ teuthology_user }}.conf"
    owner: root
    group: root
    mode: 0755

# upload custom disk monitoring scripts
- include: disk_monitoring.yml
  tags:
    - monitoring-scripts

# configure things specific to yum systems
- include: yum_systems.yml
  when: ansible_pkg_mgr == "yum"

# configure things specific to apt systems
- include: apt_systems.yml
  when: ansible_pkg_mgr == "apt"

# configure centos specific things
- include: setup-centos.yml
  when: ansible_distribution == "CentOS"

# configure red hat specific things
- include: setup-redhat.yml
  when: ansible_distribution == 'RedHat'

# configure fedora specific things
- include: setup-fedora.yml
  when: ansible_distribution == "Fedora"

# configure ubuntu specific things
- include: setup-ubuntu.yml
  when: ansible_distribution == "Ubuntu"

# configure ntp
- include: ntp.yml
  tags:
    - ntp-client

# configure pip to use our mirror
- include: pip.yml
  tags:
    - pip

# add SSH pubkeys to authorized_keys
- include: ssh_pubkeys.yml
  tags:
  - ssh
  - pubkeys
