---
# loading vars
- include: vars.yml
  tags:
    - vars
    - always

- include: user.yml
  tags:
    - user

- name: Set a high max open files limit for the teuthology user.
  template:
    src: security_limits.conf
    dest: "/etc/security/limits.d/{{ teuthology_user }}.conf"
    owner: root
    group: root
    mode: 0755

- name: Set the hostname
  include: set_hostname.yml
  when: lab_domain != ""
  tags:
    - hostname

# partition drives, if any are requested
- include: drive_partitioning.yml
  when: drive_to_partition is defined
  tags:
    - partition

# configure ssh
- include: ssh.yml
  tags:
    - ssh

# configure things specific to yum systems
- include: yum_systems.yml
  when: ansible_pkg_mgr == "yum"

# configure things specific to apt systems
- include: apt_systems.yml
  when: ansible_pkg_mgr == "apt"

# configure centos specific things
- include: setup-centos.yml
  when: ansible_distribution == "CentOS"

# configure red hat specific things
- include: setup-redhat.yml
  when: ansible_distribution == 'RedHat'

# configure fedora specific things
- include: setup-fedora.yml
  when: ansible_distribution == "Fedora"

# configure ubuntu specific things
- include: setup-ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include: setup-ubuntu-non-aarch64.yml
  when:
    ansible_distribution == "Ubuntu" and
    ansible_architecture != "aarch64"

# configure debian specific things
- include: setup-debian.yml
  when: ansible_distribution == "Debian"

# Install and configure cpan and Amazon::S3
- include: cpan.yml
  tags:
    - cpan

# upload custom disk monitoring scripts
- include: disk_monitoring.yml
  tags:
    - monitoring-scripts

# configure nagios
- include: nagios.yml
  tags:
    - nagios

- name: Get SELinux status
  command: getenforce
  register: selinux_status
  when: ansible_pkg_mgr == "yum"
  tags:
    - nagios

# configure selinux for nagios
- include: nrpe-selinux.yml
  when: selinux_status is defined and selinux_status.stdout != "Disabled"
  tags:
    - nagios

# configure ntp
- include: ntp.yml
  tags:
    - ntp-client

# configure pip to use our mirror
- include: pip.yml
  tags:
    - pip

# include resolv.conf setup
- include: resolvconf.yml
  tags:
    - resolvconf

# Touch a file to indicate we are done. This is something chef did;
# teuthology.task.internal.vm_setup() expects it.
- name: Touch /ceph-qa-ready
  file:
      path: /ceph-qa-ready
      state: touch
