---
- name: Upload nagios sudoers.d for raid utilities.
  template:
    src: nagios/90-nagios
    dest: /etc/sudoers.d/90-nagios
    owner: root
    group: root
    mode: 0440
    validate: visudo -cf %s

- name: Configure nagios nrpe settings (Ubuntu)
  lineinfile:
    dest: /etc/default/{{ nrpe_service_name }}
    regexp: "^DAEMON_OPTS"
    line: "DAEMON_OPTS=\"--no-ssl\""
  when: ansible_pkg_mgr == "apt"

- name: Configure nagios nrpe settings (RHEL/CentOS)
  lineinfile:
    dest: /etc/sysconfig/{{ nrpe_service_name }}
    regexp: "^NRPE_SSL_OPT"
    line: "NRPE_SSL_OPT=\"-n\""
  when: ansible_pkg_mgr == "yum"

- name: Check firewalld status
  command: systemctl status firewalld
  register: firewalld
  ignore_errors: true
  no_log: true
  when: ansible_pkg_mgr == "yum"

- name: Open nrpe port if firewalld enabled
  firewalld:
    port: 5666/tcp
    state: enabled
    permanent: yes
    immediate: yes
  when: ansible_pkg_mgr == "yum" and (firewalld is defined and firewalld.stdout.find('running') != -1)

- name: Upload nagios nrpe config.
  template:
    src: nagios/nrpe.cfg 
    dest: /etc/nagios/nrpe.cfg
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nagios-nrpe-server

- name: Make sure nagios nrpe service is running.
  service:
    name: "{{ nrpe_service_name }}"
    enabled: yes
    state: started
