---
- name: Remove /etc/ceph
  file:
    path: /etc/ceph
    state: absent

- include: nfs.yml
  tags:
    - nfs

- name: Edit lvm.conf to support LVM on RBD.
  lineinfile:
    dest: /etc/lvm/lvm.conf
    regexp: "# types ="
    line: 'types = [ "rbd", 16 ]'
    backrefs: yes
    state: present
