---
- name: Remove /etc/ceph
  file:
    path: /etc/ceph
    state: absent

- name: Upload weekly kernel-clean crontab.
  template:
    src: cron/kernel-clean
    dest: /etc/cron.weekly/kernel-clean
    owner: root
    group: root
    mode: 0755
  notify:
    - restart cron

# Install and configure cpan and Amazon::S3
- include: cpan.yml
  tags:
    - cpan

- name: Upload /etc/grub.d/02_force_timeout.
  template:
    src: grub.d/02_force_timeout
    dest: /etc/grub.d/02_force_timeout
    owner: root
    group: root
    mode: 0755
