---
- name: Fix broken cloud-init
  include: cloud-init.yml
  when: ansible_distribution_major_version == "6"

- name: Stop iptables
  service:
    name: iptables
    state: stopped
    enabled: no
  when: ansible_distribution_major_version == "6"

- name: Stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_distribution_major_version == "7"

- include: imitate_ubuntu.yml
