---
- name: Remove /etc/ceph
  file:
    path: /etc/ceph
    state: absent

# Install and configure cpan and Amazon::S3
- include: cpan.yml
  tags:
    - cpan

- include: nfs.yml
  tags:
    - nfs

- name: Edit lvm.conf to support LVM on RBD.
  lineinfile:
    dest: /etc/lvm/lvm.conf
    regexp: "# types ="
    line: 'types = [ "rbd", 1024 ]'
    backrefs: yes
    state: present
