---
- name: Set up static IP in /etc/hosts.
  lineinfile:
    dest: /etc/hosts
    line: "{{ ansible_default_ipv4['address'] }} {{ ansible_fqdn }} {{ ansible_hostname }}"
    regexp: "^127.0.1.1"
    backrefs: yes
    state: present

# this script was ported directly from chef.
- name: Set up static IP and 10gig interface.
  script: scripts/static-ip.sh creates=/static-ip-setup
