---
- name: Ensure the sudo group exists.
  group:
    name: sudo
    state: present

- name: Ensure the teuthology_user group exists.
  group:
    name: "{{ teuthology_user }}"
    state: present

- name: Create the teuthology user.
  user:
    name: "{{ teuthology_user }}"
    # apparently some ceph tests fail without this uid
    # https://github.com/ceph/ceph-qa-chef/commit/5678cc3893fd1cc291254e4d1abe6705e6a9bbb0
    uid: 1000
    group: sudo
    groups: "{{ teuthology_user }}"
    state: present

- name: Add a user for xfstests to test user quotas.
  user:
    name: "{{ xfstests_user }}"
    uid: 10101
    state: present
