---
# This set of tasks is intended to mount a small NVMe partition to /var/lib/ceph
# to fix http://tracker.ceph.com/issues/20910

- name: "Create /var/lib/ceph"
  file:
    path: "/var/lib/ceph"
    state: directory

- name: "Create xfs filesystem on {{ var_lib_partition }}"
  filesystem:
    dev: "{{ var_lib_partition }}"
    fstype: xfs
    force: yes
    # Don't use a version 5 superblock as it's too new for some kernels
    opts: "-m crc=0,finobt=0"

- name: "Mount {{ var_lib_partition }} to /var/lib/ceph"
  mount:
    path: "/var/lib/ceph"
    src: "{{ var_lib_partition }}"
    fstype: xfs
    # Don't fail to boot if the mount fails
    opts: defaults,nofail
    state: mounted
