---
# Tasks common to all systems that use the yum
# package manager

- name: Create remote.conf
  template:
    src: remote.conf
    dest: /etc/security/limits.d/remote.conf
    group: root
    owner: root
    mode: 0644

- name: Set mode on /etc/fuse.conf
  file:
    path: /etc/fuse.conf
    mode: 0644
    state: touch
  changed_when: false

- name: Configure /etc/sudoers.
  template:
    src: sudoers
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0440
    validate: visudo -cf %s
  tags:
    - sudoers

- name: Configure /etc/security/limits.conf
  template:
    src: limits.conf
    dest: /etc/security/limits.conf
    group: root
    owner: root
    mode: 0644

- name: Setup local repo files.
  include: yum/repos.yml
  tags:
    - repos

- name: Perform package related tasks.
  include: yum/packages.yml
  tags:
    - packages

- name: Enable SELinux
  selinux: state=permissive policy=targeted
  tags:
    - selinux
