---
- name: Make sure gdisk is installed
  package:
    name: gdisk
    state: present

- name: Set root disk
  set_fact:
    root_disk: "{{ item.device|regex_replace('[0-9]+', '') }}"
  with_items: "{{ ansible_mounts }}"
  when: item.mount == '/'

- name: Compile list of non-root partitions
  shell: "lsblk --list --noheadings | grep part | grep -v {{ root_disk|regex_replace('/dev/', '') }} | awk '{ print $1 }'"
  register: non_root_partitions

## http://tracker.ceph.com/issues/20533
## Trusty version of wipefs lacks --force option
- name: Wipe filesystems on non-root partitions
  shell: "wipefs --force --all /dev/{{ item }} || wipefs --all /dev/{{ item }}"
  with_items: "{{ non_root_partitions.stdout_lines }}"
  when: non_root_partitions|length > 0

## See https://github.com/ceph/ceph-ansible/issues/759#issue-153248281
- name: Zap all non-root disks
  shell: "sgdisk --zap-all /dev/{{ item.key }} || sgdisk --zap-all /dev/{{ item.key }}"
  with_dict: "{{ ansible_devices }}"
  when: item.key not in root_disk

- name: Remove all LVM data
  shell: "dmsetup remove_all --force"
