---
## Common tasks

# Most of our public-facing hosts are running Ubuntu.
# use_ufw defaults to false but is overridden in inventory host_vars
- include: ufw.yml
  when: use_ufw == true
  tags:
    - always

- include: fail2ban.yml
  tags:
    - always
  when: use_fail2ban == true

- name: Disable password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart sshd

## Individual host tasks

# local_action in the task after this causes 'ansible_host' to change to 'localhost'
# we set a temporary variable here to search for in the local_action task
- set_fact:
    target_host: "{{ ansible_host }}"

- name: Check for host-specific playbooks
  local_action: "stat path=roles/public_facing/tasks/{{ target_host }}.yml"
  register: host_playbook

- name: Include any host-specific playbooks if present
  include: "{{ ansible_host }}.yml"
  when: host_playbook.stat.exists
