---
- name: Include secrets
  include_vars: "{{ secrets_path | mandatory }}/nameserver.yml"
  no_log: true
  tags:
    - always

# Install and update system packages
- import_tasks: packages.yml
  tags:
    - packages

# Configure firewalld
- import_tasks: firewall.yml
  tags:
    - firewall

# Configure host as NTP server if desired
- import_tasks: ntp_server.yml
  when: nameserver_as_ntp_server == true
  tags:
    - ntp-server

- name: Enable and start ntpd
  service:
    name: ntpd
    state: started
    enabled: yes
  tags:
    - always

# DDNS updates fail to create or edit jnl files without this
- name: Ensure permissions set for /var/named/zones
  file:
    path: /var/named/zones
    owner: named
    group: named
  tags:
    - always

# Configure BIND
- import_tasks: config.yml
  tags:
    - config

# Compile and write zone files
- import_tasks: records.yml
  tags:
    - records
  when: (named_conf_slave is undefined) or
        (named_conf_slave is defined and named_conf_slave == false)
