---
- name: Include secrets
  include_vars: "{{ secrets_path | mandatory }}/nameserver.yml"
  no_log: true
  tags:
    - always

# Install and update system packages
- include: packages.yml
  tags:
    - packages

- name: Enable and start ntpd
  service:
    name: ntpd
    state: started
    enabled: yes
  tags:
    - always

# DDNS updates fail to create or edit jnl files without this
- name: Ensure permissions set for /var/named/zones
  file:
    path: /var/named/zones
    owner: named
    group: named
  tags:
    - always

# Configure firewalld
- include: firewall.yml
  tags:
    - firewall

# Configure BIND
- include: config.yml
  tags:
    - config

# Compile and write zone files
- include: records.yml
  tags:
    - records
  when: (named_conf_slave is undefined) or
        (named_conf_slave is defined and named_conf_slave == false)
