---
- name: restart ntp
  service:
    name: "{{ ntp_service_name }}" 
    state: restarted

- name: restart ssh
  service:
    name: "{{ ssh_service_name }}"
    state: restarted

- name: start rpcbind
  service:
    name: rpcbind
    state: started
    enabled: yes
  when: start_rpcbind

- name: restart nfs-server
  service:
    name: "{{ nfs_service }}"
    state: restarted

- name: restart cron
  service:
    name: cron
    state: restarted

- name: restart nagios-nrpe-server
  service:
    name: "{{ nrpe_service_name }}"
    state: restarted
