---
distros:
  # Distros with empty iso values will be skipped. These dicts will be 
  # updated with same-named items in an 'extra_distros' var, which can be 
  # set in the secrets repo.
  "RHEL-6.6-Server-x86_64":
      iso: ""
  "RHEL-7.0-Server-x86_64":
      iso: ""
  "RHEL-7.1-Server-x86_64":
      iso: ""
  "CentOS-7-x86_64":
      iso: http://ftp.linux.ncsu.edu/pub/CentOS/7/isos/x86_64/CentOS-7-x86_64-DVD-1503-01.iso
      kickstart: cephlab_rhel.ks
  "CentOS-6.6-x86_64":
      iso: http://ftp.linux.ncsu.edu/pub/CentOS/6.6/isos/x86_64/CentOS-6.6-x86_64-bin-DVD1.iso
      kickstart: cephlab_rhel.ks
  "Ubuntu-12.04-server-x86_64":
      iso: "http://releases.ubuntu.com/12.04/ubuntu-12.04.5-server-amd64.iso"
      kickstart: cephlab_ubuntu.preseed
      kernel_options: "netcfg/choose_interface=auto biosdevname=0 console=tty0 console=ttyS1,115200"
      kernel_options_post: "pci=realloc=off console=tty0 console=ttyS1,115200"
  "Ubuntu-14.04-server-x86_64":
      iso: "http://releases.ubuntu.com/14.04/ubuntu-14.04.2-server-amd64.iso"
      kickstart: cephlab_ubuntu.preseed
      kernel_options: "netcfg/choose_interface=auto biosdevname=0 console=tty0 console=ttyS1,115200"
      kernel_options_post: "pci=realloc=off console=tty0 console=ttyS1,115200"
  "Ubuntu-15.04-server-x86_64":
      iso: "http://releases.ubuntu.com/15.04/ubuntu-15.04-server-amd64.iso"
      kickstart: cephlab_ubuntu.preseed
      kernel_options: "netcfg/choose_interface=auto biosdevname=0 console=tty0 console=ttyS1,115200"
      kernel_options_post: "pci=realloc=off console=tty0 console=ttyS1,115200"
