---
# This is to prevent normal (read: human) users from ending up with UID 1000,
# which testnodes needs for the teuthology user.
- name: Set UID_MIN to 1001
  lineinfile:
    dest: /etc/login.defs
    regexp: "^UID_MIN"
    line: "UID_MIN                  1001"

- name: Create all admin users with sudo access.
  user:
    name: "{{ item.name }}"
    groups: sudo
    shell: /bin/bash
    state: present
  with_items: managed_admin_users

- name: Create all users without sudo access.
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    state: present
  with_items: managed_users
