---
- include: filter_users.yml
  tags:
    - always

- include: create_users.yml
  tags:
    - user

- include: update_keys.yml
  tags:
    - pubkeys

- include: revoke_users.yml
  tags:
    - user
    - revoke
