---
- import_tasks: filter_users.yml
  tags:
    - always

- import_tasks: create_users.yml
  tags:
    - user

- import_tasks: update_keys.yml
  tags:
    - pubkeys

- import_tasks: revoke_users.yml
  tags:
    - user
    - revoke
