---
- name: Update authorized_keys for each user.
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"
  with_items: managed_users|list + managed_admin_users|list
  # Register and retry to work around transient githubusercontent.com issues
  register: ssh_key_update
  until: ssh_key_update|success
  # try for 2 minutes to retrieve the key before failing
  retries: 24
  delay: 5
