---
- name: enable rel-eng repositories
  template:
    src: eng-rhel-7.repo
    dest: /etc/yum.repos.d/eng-rhel-7.repo
    owner: root
    group: root
    mode: 0644

- name: install puddle and dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - puddle
    - rcm-kerberos
    - krb5-workstation
    - kstart

- name: Add a new unprivileged UID to run puddle
  user:
    name: "{{ puddle_user }}"
    state: present
    home: '/etc/puddle'
    createhome: no
    system: yes
