---
- fail:
    msg: "Puddle is only relevant on RHEL"
  when: ansible_distribution != 'RedHat'

# install puddle
- include: install.yml
  tags:
    - install-puddle

# configure NFS
- include: nfs.yml

# configure puddle
- include: configure.yml
  tags:
    - configure-puddle

# install and configure web server
- include: nginx.yml
  tags:
    - nginx

# install and configure distill
- include: distill/install.yml
  tags:
    - install-distill

- include: distill/configure.yml
  tags:
    - configure-distill
