---
- fail:
    msg: "Puddle is only relevant on RHEL"
  when: ansible_distribution != 'RedHat'

# install puddle
- import_tasks: install.yml
  tags:
    - install-puddle

# configure NFS
- import_tasks: nfs.yml

# configure puddle
- import_tasks: configure.yml
  tags:
    - configure-puddle

# install and configure web server
- import_tasks: nginx.yml
  tags:
    - nginx

# install and configure distill
- import_tasks: distill/install.yml
  tags:
    - install-distill

- import_tasks: distill/configure.yml
  tags:
    - configure-distill

# install and configure rsyncd
- import_tasks: rsync.yml
  tags:
    - rsync
