---

- name: install nfs client
  yum:
    name: nfs-utils
    state: present

- name: Mount /mnt/redhat
  mount:
    name: /mnt/redhat
    src: "{{ puddle.mnt_redhat_nfs_src }}"
    fstype: nfs
    opts: 'ro,nosuid,nodev,hard,intr,bg,noatime,nodiratime,nfsvers=3,tcp,rsize=8192,wsize=8192'
    state: mounted
