---
- name: install rsync
  yum:
    name: rsync
    state: present

- name: configure rsyncd
  template:
    src: rsyncd.conf
    dest: /etc/rsyncd.conf
  notify:
   - restart rsyncd

- name: start the rsyncd service
  service:
    name: rsyncd
    state: started
    enabled: yes
