---
# Restart networking
- name: restart networking
  service:
    name: network
    state: restarted

# Restart fail2ban
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

# Reload fail2ban
- name: reload fail2ban
  service:
    name: fail2ban
    state: reloaded

# Restart OpenVPN
- name: restart openvpn
  service:
    name: "openvpn@{{ openvpn_server_name }}"
    state: restarted

# Restart rsyslog
- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
