---
# We use these scripts to check to see if any of our test nodes have bad disks

# Ignore errors in case there are no repos enabled and package install fails
- name: Make sure smartmontools is installed
  package:
    name: smartmontools
    state: latest
  ignore_errors: true

- name: Upload megacli and cli64 for raid monitoring and smart.pl to /usr/sbin/.
  copy:
    src: "../files/sbin/{{ item }}"
    dest: "/usr/sbin/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - megacli
    - cli64

- name: Create /usr/libexec.
  file:
    path: /usr/libexec
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Upload custom netsaint scripts for raid/disk/smart/monitoring to /usr/libexec/.
  copy:
    src: "../files/libexec/{{ item }}"
    dest: "/usr/libexec/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - smart.sh
    - raid.pl
    - diskusage.pl
