---
# loading major version specific vars
- name: Including major version specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml"
    - empty.yml
  tags:
    - vars

# configure Red Hat entitlements with subscription-manager
- include: rhel-entitlements.yml
  when: ansible_distribution == 'RedHat'
  tags:
    - entitlements
