---
- name: Include package type specific vars.
  include_vars: "{{ ansible_pkg_mgr }}_systems.yml"
  tags:
    - vars

# configure pip to use our mirror
- include: pip.yml

- name: Set a high max open files limit
  template:
    src: security_limits.conf
    dest: /etc/security/limits.d/ubuntu.conf
    owner: root
    group: root
    mode: 0755

# configure ntp
- include: ntp.yml
  tags:
    - ntp-client

# upload custom disk monitoring scripts
- include: disk_monitoring.yml
  tags:
    - monitoring-scripts

# configure red hat specific things
- include: setup-redhat.yml
  when: ansible_os_family == 'RedHat'
