---
# loading major version specific vars
- name: Including major version specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml"
    - empty.yml
  tags:
    - vars
    # We need these vars for the entitlements tag to work
    - entitlements

# configure Red Hat entitlements with subscription-manager
- include: rhel-entitlements.yml
  when: ansible_distribution == 'RedHat'
  tags:
    - entitlements

# configure Kerberos
- include: kerberos.yml
  tags:
    - kerberos

# create and manage epel.repo
- include: epel.yml
  when:
    ansible_distribution == "CentOS" or
    ansible_distribution == 'RedHat'
  tags:
    - epel
    - repos
