---
# Register a RHEL-based system with subscription-manager.

- name: Include Red Hat encrypted variables.
  include_vars: "{{ secrets_path | mandatory }}/entitlements.yml"
  no_log: true
  tags:
    - vars

- name: Determine if node is registered with subscription-manager.
  command: subscription-manager identity
  register: subscription
  ignore_errors: true
  changed_when: false
  no_log: true

- name: Register with subscription-manager.
  command: subscription-manager register
           --activationkey={{ subscription_manager_activationkey }}
           --org={{ subscription_manager_org }}
  no_log: true
  when: subscription.rc != 0
