---
- name: Including version specific variables.
  include_vars: "rhel_{{ ansible_distribution_version }}.yml"
  tags:
    - vars

- name: Setup local repo files.
  include: redhat/repos.yml
  tags:
    - repos

- name: Register with subscription-manager.
  include: redhat/entitlements.yml
  tags:
    - entitlements

- name: Installing packages with yum.
  include: redhat/packages.yml
  tags:
    - packages

- name: Create remote.conf
  template:
    src: remote.conf
    dest: /etc/security/limits.d/remote.conf
    group: root
    owner: root
    mode: 0644

- name: Include version specific tasks.
  include: redhat/rhel_7.0.yml
  when: ansible_distribution_version == "7.0"
