---
- name: Including version specific variables.
  include_vars: "rhel_{{ ansible_distribution_version }}.yml"

- name: Setup local repo files.
  include: redhat/repos.yml

- name: Register with subscription-manager.
  include: redhat/entitlements.yml
