---
- name: Including version specific variables.
  include_vars: "rhel_{{ ansible_distribution_version }}.yml"
  tags:
    - vars

- name: Setup local repo files.
  include: redhat/repos.yml
  tags:
    - repos

- name: Register with subscription-manager.
  include: redhat/entitlements.yml
  tags:
    - entitlements

- name: Installing packages with yum.
  include: redhat/packages.yml
  tags:
    - packages

- name: Stop firewalld
  service:
    name: firewalld
    state: stopped
