---
- name: add ceph distill config dir
  file:
    path: /etc/distill/
    owner: root
    group: root
    mode: 0755
    state: directory

# This repository contains distill's configuration files.
- name: clone rcm-metadata.git
  git:
    dest: /etc/distill/rcm-metadata
    repo: "{{ distill.rcm_metadata_repo }}"
    update: no
    version: ceph

# distill requires this symlink in order to run.
- name: symlink /mnt/brew
  file:
    src: /mnt/redhat/brewroot
    dest: /mnt/brew
    owner: root
    group: root
    state: link

- name: create destinations (targets) for distill trees (composes)
  file:
    path: /var/www/{{ ansible_hostname }}/htdocs/distill/{{ item }}-trees
    owner: "{{ puddle_user }}"
    mode: 0755
    state: directory
  with_items:
    - 1.3-candidate
    # 1.3-pending

- name: add ceph wrapper script for run-distill
  template:
    src: '../../templates/distill/ceph-distill'
    dest: '/usr/local/bin/ceph-distill'
    owner: root
    group: root
    mode: 0755
