---
# There have been instances where iptables is installed on EL7 testnodes.
# This task will make sure both services are stopped and disabled regardless
# of OS version.

- name: Stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: true

- name: Stop and disable iptables
  service:
    name: iptables
    state: stopped
    enabled: no
  ignore_errors: true
