---
- name: Work around https://bugzilla.redhat.com/show_bug.cgi?id=1234967
  command: rpm -e ceph-debuginfo
  tags:
    - remove-ceph

- name: Ensure ceph packages are not present.
  yum:
    name: "{{ item }}"
    state: absent
  with_items: ceph_packages
  tags:
    - remove-ceph

- name: Install packages
  yum:
    name: "{{ item }}"
    state: present 
  with_items: packages
  when: packages|length > 0

- name: Remove packages
  yum:
    name: "{{ item }}"
    state: absent
  with_items: packages_to_remove
  when: packages_to_remove|length > 0

- name: Upgrade packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items: packages_to_upgrade
  when: packages_to_upgrade|length > 0
