---
pip_mirror_url: "http://{{ mirror_host }}/pypi/simple"

# repos common to a major version
common_yum_repos: {}

# version specific repos, defined in the version specific vars file
yum_repos: {}

# list of packages to install
# packages are defined in the pkg manager
# specific var files.
packages: []

packages_to_remove: []
packages_to_upgrade: []

# the user teuthology will use
teuthology_user: "ubuntu"
xfstests_user: "fsgqa"

# some distros need to start rpcbind before
# trying to use nfs while others don't.
start_rpcbind: true

# set to true if /etc/fstab must be modified to persist things like
# mount options, which is useful for long lived bare metal machines,
# less useful for virtual machines that are re-imaged before each job
modify_fstab: true
