---
packages_to_upgrade:
  - leveldb

packages_to_remove:
  - ceph-libs

packages:
  - '@core'
  - yum-plugin-priorities
  - redhat-lsb
  - sysstat
  - gdb
  - git-all
  - python-configobj
  # for running ceph
  - libedit
  - openssl-devel
  - google-perftools-devel
  - boost-thread
  - xfsprogs
  - gdisk
  - parted
  - libgcrypt
  - cryptopp-devel
  - cryptopp
  ###
  # for ceph-deploy
  - python-virtualenv
  ###
  # for setting BIOS settings
  - smbios-utils
  ###
  - openssl
  - libuuid
  - fcgi-devel
  - btrfs-progs
  # for compiling helpers
  - libatomic_ops-devel
  ###
  # used by workunits
  - attr
  - valgrind
  - python-nose
  - mpich2
  - mpich2-devel
  - ant
  - dbench
  - bonnie++
  ###
  # used by the xfstests tasks
  - libtool
  - automake
  - gettext
  - uuid-devel
  - libacl-devel
  - bc
  - xfsdump
  ###
  # for blktrace and seekwatcher
  - blktrace
  - numpy
  - python-matplotlib
  # for json_xs to investigate JSON by hand
  - perl-JSON
  # for pretty-printing xml
  - perl-XML-Twig
  # for java bindings, hadoop, etc.
  - java-1.8.0-openjdk-devel
  - junit
  # for disk/etc monitoring
  - nrpe
  - nagios-plugins-all
  - smartmontools
  # for nfs
  - nfs-utils
  # python-pip is installed via roles/testnode/tasks/pip.yml on other rpm-based distros
  - python-pip
