---
# vars specific to any rhel 7.x version

common_yum_repos:
  lab-extras:
    name: "lab-extras"
    baseurl: "http://{{ mirror_host }}/lab-extras/rhel7/"
    enabled: 0
    gpgcheck: 0
    priority: 2

packages:
  - '@core'
  - '@base'
  - yum-plugin-priorities
  - yum-plugin-fastestmirror
  - redhat-lsb
  - sysstat
  - gdb
  - git-all
  - python-configobj
  - libedit
  - openssl098e
  - boost-thread
  - xfsprogs
  - xfsprogs-devel
  - gdisk
  - parted
  - libgcrypt
  - fuse
  - fuse-libs
  - openssl
  - libuuid
  - btrfs-progs
  - attr
  - valgrind
  - python-nose
  - mpich
  - ant
  - lsof
  #- iozone
  - libtool
  - automake
  - gettext
  - libuuid-devel
  - libacl-devel
  - bc
  - xfsdump
  - blktrace
  - numpy
  - python-matplotlib
  - qemu-kvm
  - usbredir
  - genisoimage
  - httpd
  - httpd-devel
  - httpd-tools
  - mod_ssl
  - libevent-devel
  - perl-XML-Twig
  - java-1.6.0-openjdk-devel
  - junit4
  - smartmontools
  - nfs-utils
  # for xfstests
  - ncurses-devel
  # for s3 tests
  - python-devel
  - python-virtualenv

epel_packages:
  - gperftools-devel
  - cryptopp-devel
  - cryptopp
  - dbench
  - fcgi
  - fuse-sshfs
  - perl-JSON-XS

nfs_service: nfs-server
