---
# This is temporarily disabled because of:
# http://tracker.ceph.com/issues/13572
#apt_repos:
#  # blkin libraries, only trusty has new enough lttng for these
#  - "deb [arch=amd64] http://{{ mirror_host }}/blkin/ trusty main"

packages:
  - libboost-thread1.54.0
  - mpich
  - qemu-system-x86
#  - blkin
  - lttng-tools
  ###
  # for setting BIOS settings
  ###
  - libcrypto++9
  ###
  # used by workunits
  - mpich2
  - libmpich2-dev

non_aarch64_packages:
  - libgoogle-perftools4
  - iozone3
  - dmapi
  - libssl0.9.8
