---
# This is temporarily disabled because of:
# http://tracker.ceph.com/issues/13572
#apt_repos:
#  # blkin libraries, only trusty has new enough lttng for these
#  - "deb [arch=amd64] http://{{ mirror_host }}/blkin/ trusty main"

packages:
  - libgoogle-perftools4
  - libboost-thread1.54.0
  - mpich
#  - blkin
  - lttng-tools
