---
- name: Enable http and https using firewalld
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items:
    - http
    - https
  tags:
    - firewall
